version: '2.4'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db-mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=null

volumes:
  db-mysql:
